### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by pmayd** [tumb1er/coverage2clover#23]
Using your tool creates above error message right away.

Steps to reproduce:
```BASH
coverage run --source=<my-package> -m xmlrunner discover -o test-reports
coverage xml
coverage2clover -i coverage.xml -o clover.xml
```

Error:

```
coverage2clover -i coverage.xml -o clover.xml
Traceback (most recent call last):
  File "/Users/miay/anaconda3/envs/greta/bin/coverage2clover", line 8, in <module>
    sys.exit(main())
  File "/Users/miay/anaconda3/envs/greta/lib/python3.7/site-packages/clover/coverage2clover.py", line 23, in main
    cov.open(inputfile)
  File "/Users/miay/anaconda3/envs/greta/lib/python3.7/site-packages/clover/__init__.py", line 137, in open
    c.count_loc(sources)
  File "/Users/miay/anaconda3/envs/greta/lib/python3.7/site-packages/clover/__init__.py", line 65, in count_loc
    filename = os.path.join(source, self.filename)
  File "/Users/miay/anaconda3/envs/greta/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by tumb1er** [comment]
Can't reproduce:
```
$ coverage run --source=fffw -m xmlrunner discover -o test-reports
No module named xmlrunner.__main__; 'xmlrunner' is a package and cannot be directly executed
```
Could you please provide more information about your environment?

**Comment by pmayd** [comment]
Ah I am sorry, of course. I need xml reports for my tests, but unittest is not able to produce them out of the box (instead of pytest). So to create an xml report in the first place, I use xmlrunner for Python3: https://github.com/xmlrunner/unittest-xml-reporting as a replacement for unittest.

So that is `pip install unittest-xml-reporting`. This replaces `python -m unittest discover` with `python -m xmlrunner discover` and will produce an xml for each unittest file.

**Comment by tumb1er** [comment]
Well, still can't reproduce this. Now for my project `coverage xml` & `coverage2clover` run successfully.

Looks like some modules in your `coverage.xml` doesn't have filename attribute.
