### ISSUE TITLE
Move CI to GitHub Actions

### ISSUE THREAD

**Issue by tumb1er** [tumb1er/coverage2clover#34]
travis-ci does not leave comments under PR, so it's time waste going to travis-ci.org and check every PR

**Comment by gauravojha** [comment]
@tumb1er  if you don't mind, can I take a stab at this issue (unless of course you have already started on this)?

**Comment by tumb1er** [comment]
Yes, you may look at https://github.com/just-work/django-celery-rpc/blob/master/.github/workflows/build.yml as an example of what I mean.
