### ISSUE TITLE
[Question]: EOL Python Support

### ISSUE THREAD

**Issue by gauravojha** [tumb1er/coverage2clover#38]
Python 3.5 reached its EOL on 13th Sept, 2020

```
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
```

Just curious as to the release support for the packages. Do you plan to continue publishing packages for EOL Python versions as well?

**Comment by tumb1er** [comment]
I think python-3.5 support may be officially dropped.
